kind: pipeline
name: default

steps:
- name: test
  image: node:11
  commands:
  - npm install
  - npm test

- name: Publish to NPM
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
  when:
    status:
    - success
    event:
    - tag

- name: coveralls
  image: lizheming/drone-coveralls
  settings:
    token:
      from_secret: coveralls_token
    files:
    - ./coverage/lcov.info
