kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test

- name: coveralls
  image: lizheming/drone-coveralls
  settings:
    token:
      from_secret: coveralls_token
    files:
    - ./coverage/lcov.info
