language: node_js
node_js:
- '5'
- '6'
- '7'
install:
- npm install -g yarn
- yarn install
script:
- npm test
deploy:
  provider: npm
  email: stef@azsiaz.tech
  api_key:
    secure: RC4FXob02cL87W3XPJxCIhCVOqXgaFGIuWxWU0Drph0GHZzZx18VvUtZvBLjFkKwYSwfeOxHpW+gjw3z3elBXoFBmZcdmrC6drtcKCDv3DZruYbWU5snYlXRs3aewBVO0bHqpvZvFamu5lZ4N+YycxEzIEZTGWW9hG+pJXA1u7bOGKOy4BLlkynXIkXiov9Y5K8qdLW1Htni9Hlsl+m4DviRkheNZE9XWapRz4zRQet+hU/aPmAItTDEfykGEg3HVNe7u2RSixSMibkvDZpg7a4+FO/y2qQqDDEntsfIcOtDEPpFwu9jFjP2ufR1At4+fpkYhbLsdb0z8kxtsqPdtuva558u/pVibPAbjbjPR/74lBd27KxbYQqEEwgEhjKfIPLNTrg3n3O67n8995nCaVg8S51eBTZj/JgYoRXNNOpr1Cm54MGNR06EaAeQOpX7V8yIHWrmD+51xjuyFjFWIEICE8OYlxSdv/cVM/Bc2Oj1EBDGZxpHPxL6KPWmbsllz3+TlS5n776Ey4FNM75alQWwZHSSKiI8peqYwWvz6mpQQAa/rgP7R85n4ZcyRFqWt1evoJmNLdiNXQTySOWQTkM6ZW1VoW2+r7yeJj4mipwvpEz0Ow9lFkfO6DXFq9WFYIGar9RQOP26TJSh2AKUyJm90A3yZBT9rjVYSs5OTYQ=
  on:
    tags: true
    repo: AzSiAz/MangaTown-Data
